[build-system]
requires = ["maturin>=1.4,<2.0"]
build-backend = "maturin"

[project]
name = "cyclegraph_core"
version = "0.1.0"
requires-python = ">=3.9"
description = "CycleGraph core with PyO3 bindings"
authors = [{ name = "Johnny Stroemoe" }]
