[package]
name = "cyclegraph_core"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "CycleGraph core (Rust+pyo3) for analysis metrics and CGS scoring"
readme = "../README.md"

[lib]
name = "cyclegraph_core"
crate-type = ["cdylib", "rlib"]

[dependencies]
pyo3 = { version = "0.20", features = ["extension-module"] }


serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"

[dev-dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
csv = "1.3"

[profile.release]
lto = "thin"
codegen-units = 1

[build-dependencies]
maturin = "0.13"